global:

  scrape_interval: 15s

  evaluation_interval: 15s


scrape_configs:

  - job_name: "hospital-backend"

    metrics_path: "/metrics"

    static_configs:

      - targets:

          - "hospital-backend.hospital.svc.cluster.local:5000"