apiVersion: v1
kind: Service

metadata:
  name: hospital-backend
  namespace: hospital

spec:

  type: ClusterIP

  selector:

    app: hospital-backend

  ports:

    - name: http

      protocol: TCP

      port: 5000

      targetPort: 5000